defaults: &defaults
  # year doesn't matter as long as it is in the past, cronjob creates new date incrementing exactly one year
  begin_study_year: '2009-09-01'


  mongoose_ideal_costs: 0.29
  liquor_time: '16:00'
  ideal_relation_code: "473"
  payment_condition_code: "02"
  mongoose_ledger_number: "8002"
  accountancy_ledger_number: "5007"
  accountancy_cost_location: "TRX"


  intro:
    membership: [1]
    activities: []

  additional_positions:
    committee: ['fotograaf','pr']
    moot: []

development:
  <<: *defaults

test:
  <<: *defaults

staging:
  <<: *defaults

production:
  <<: *defaults
