# Development
# Running on local machine
development:
  adapter: mysql2
  database: koala-development
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  socket: <%= ENV['DATABASE_SOCKET'] %>
  host: <%= ENV['DATABASE_HOST'] %>
  pool: 5
  timeout: 5000
  encoding: utf8mb4

# test
# Version used by circleci
test:
  adapter: mysql2
  database: koala-test
  host:  127.0.0.1
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  socket: <%= ENV['DATABASE_SOCKET'] %>
  pool: 5
  timeout: 5000
  encoding: utf8mb4

# Production
# Version for public use running on svsticky.nl
production:
  adapter: mysql2
  database: koala
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  socket: /var/run/mysqld/mysqld.sock
  host: localhost
  pool: 5
  timeout: 5000
  encoding: utf8mb4

# Staging
# Version for QA running on dev.svsticky.nl
staging:
  adapter: mysql2
  database: koala
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  socket: /var/run/mysqld/mysqld.sock
  host: localhost
  pool: 5
  timeout: 5000
  encoding: utf8mb4
