# Development
# Running on local machine
development:
  adapter: mysql2
  database: koala-development
  host: localhost
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  socket: <%= ENV['DATABASE_SOCKET'] %>
  pool: 5
  timeout: 5000
  encoding: utf8

# test
# Version used by circleci
test:
  adapter: mysql2
  database: koala-test
  host: localhost
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  socket: <%= ENV['DATABASE_SOCKET'] %>
  pool: 5
  timeout: 5000
  encoding: utf8

# Production
# Version for public use running on svsticky.nl
production:
  adapter: mysql2
  database: koala
  host: localhost
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  socket: /var/run/mysqld/mysqld.sock
  pool: 5
  timeout: 5000
  encoding: utf8

# Staging
# Version for QA running on dev.svsticky.nl
staging:
  adapter: mysql2
  database: koala
  host: localhost
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  socket: /var/run/mysqld/mysqld.sock
  pool: 5
  timeout: 5000
  encoding: utf8
