# Development
# Running on local machine
development:
  adapter: postgresql
  database: koala-development
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  socket: <%= ENV['POSTGRES_SOCKET'] %>
  port: <%= ENV['DATABASE_PORT'] %>
  host: localhost
  pool: 5
  timeout: 5000

# test
# Version used by circleci and the local tests
test:
  adapter: postgresql
  database: koala-test
  host: localhost
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  port: <%= ENV['DATABASE_PORT'] %>
  pool: 5
  timeout: 5000

# Production
# Version for public use running on svsticky.nl
production:
  adapter: mysql2
  database: koala
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  socket: <%= ENV['DATABASE_SOCKET'] %>
  host: localhost
  pool: 5
  timeout: 5000
  encoding: utf8mb4

# Staging
# Version for QA running on dev.svsticky.nl
staging:
  adapter: postgresql
  database: koala
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  socket: <%= ENV['DATABASE_SOCKET'] %>
  host: ''
  pool: 5
  timeout: 5000
